/// Flutter icons ToneMasterIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ToneMasterIcons
///      fonts:
///       - asset: fonts/ToneMasterIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ToneMasterIcons {
  ToneMasterIcons._();

  static const _kFontFam = 'ToneMasterIcons';
  static const String? _kFontPkg = null;

  static const IconData fourth_tone = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData second_tone = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData third_tone = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fifth_tone = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData first_tone = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
