// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK4Ub2o7O4oC6yFp20R-A9VCl9nZ5Trw4',
    appId: '1:1067587955326:web:5f75f35c0121a2c9cfc62f',
    messagingSenderId: '1067587955326',
    projectId: 'tonemaster-5c394',
    authDomain: 'tonemaster-5c394.firebaseapp.com',
    storageBucket: 'tonemaster-5c394.appspot.com',
    measurementId: 'G-PT1W4SBHMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsTnzNU1rgAIUjMz8ni9-TOYCX5zq1iZs',
    appId: '1:1067587955326:android:3bb3b82b86eada48cfc62f',
    messagingSenderId: '1067587955326',
    projectId: 'tonemaster-5c394',
    storageBucket: 'tonemaster-5c394.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV7rhLrMlpKIEzZe2zFJIP28EZx3E35hE',
    appId: '1:1067587955326:ios:4dee6cc2212207c3cfc62f',
    messagingSenderId: '1067587955326',
    projectId: 'tonemaster-5c394',
    storageBucket: 'tonemaster-5c394.appspot.com',
    iosClientId: '1067587955326-gi4mflumvqja96043hmeqd3dvjs7k3cl.apps.googleusercontent.com',
    iosBundleId: 'com.tonemaster.app',
  );
}
